// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blox/options.proto

package com.logicblox.common.protocol.blox;

public final class Options {
  private Options() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.logicblox.common.protocol.blox.Options.isConstructor);
    registry.add(com.logicblox.common.protocol.blox.Options.useDictionary);
    registry.add(com.logicblox.common.protocol.blox.Options.useDictionaryPackage);
    registry.add(com.logicblox.common.protocol.blox.Options.mapWithKey);
    registry.add(com.logicblox.common.protocol.blox.Options.inlined);
    registry.add(com.logicblox.common.protocol.blox.Options.set);
    registry.add(com.logicblox.common.protocol.blox.Options.lifetime);
  }
  public static final int IS_CONSTRUCTOR_FIELD_NUMBER = 60000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> isConstructor = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int USE_DICTIONARY_FIELD_NUMBER = 60001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> useDictionary = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int USE_DICTIONARY_PACKAGE_FIELD_NUMBER = 60002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> useDictionaryPackage = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int MAP_WITH_KEY_FIELD_NUMBER = 60003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> mapWithKey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int INLINED_FIELD_NUMBER = 60004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> inlined = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SET_FIELD_NUMBER = 60005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> set = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int LIFETIME_FIELD_NUMBER = 70000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> lifetime = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022blox/options.proto\022\014blox.options\032 goog" +
      "le/protobuf/descriptor.proto:7\n\016is_const" +
      "ructor\022\035.google.protobuf.FieldOptions\030\340\324" +
      "\003 \001(\010:7\n\016use_dictionary\022\035.google.protobu" +
      "f.FieldOptions\030\341\324\003 \001(\010:?\n\026use_dictionary" +
      "_package\022\035.google.protobuf.FieldOptions\030" +
      "\342\324\003 \001(\t:5\n\014map_with_key\022\035.google.protobu" +
      "f.FieldOptions\030\343\324\003 \001(\t:0\n\007inlined\022\035.goog" +
      "le.protobuf.FieldOptions\030\344\324\003 \001(\010:,\n\003set\022" +
      "\035.google.protobuf.FieldOptions\030\345\324\003 \001(\010:3",
      "\n\010lifetime\022\037.google.protobuf.MessageOpti" +
      "ons\030\360\242\004 \001(\tB$\n\"com.logicblox.common.prot" +
      "ocol.blox"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    isConstructor.internalInit(descriptor.getExtensions().get(0));
    useDictionary.internalInit(descriptor.getExtensions().get(1));
    useDictionaryPackage.internalInit(descriptor.getExtensions().get(2));
    mapWithKey.internalInit(descriptor.getExtensions().get(3));
    inlined.internalInit(descriptor.getExtensions().get(4));
    set.internalInit(descriptor.getExtensions().get(5));
    lifetime.internalInit(descriptor.getExtensions().get(6));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
