// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blox/connect/Exception.proto

package com.logicblox.connect;

public final class ProtoBufException {
  private ProtoBufException() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExceptionContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blox.connect.ExceptionContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    boolean hasWorkspace();
    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    com.logicblox.connect.ProtoBufException.WorkspaceException getWorkspace();
    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder getWorkspaceOrBuilder();
  }
  /**
   * Protobuf type {@code blox.connect.ExceptionContainer}
   */
  public static final class ExceptionContainer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:blox.connect.ExceptionContainer)
      ExceptionContainerOrBuilder {
    // Use ExceptionContainer.newBuilder() to construct.
    private ExceptionContainer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExceptionContainer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExceptionContainer defaultInstance;
    public static ExceptionContainer getDefaultInstance() {
      return defaultInstance;
    }

    public ExceptionContainer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExceptionContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 18: {
              com.logicblox.connect.ProtoBufException.WorkspaceException.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = workspace_.toBuilder();
              }
              workspace_ = input.readMessage(com.logicblox.connect.ProtoBufException.WorkspaceException.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(workspace_);
                workspace_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_ExceptionContainer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_ExceptionContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicblox.connect.ProtoBufException.ExceptionContainer.class, com.logicblox.connect.ProtoBufException.ExceptionContainer.Builder.class);
    }

    public static com.google.protobuf.Parser<ExceptionContainer> PARSER =
        new com.google.protobuf.AbstractParser<ExceptionContainer>() {
      public ExceptionContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExceptionContainer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExceptionContainer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKSPACE_FIELD_NUMBER = 2;
    private com.logicblox.connect.ProtoBufException.WorkspaceException workspace_;
    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    public boolean hasWorkspace() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    public com.logicblox.connect.ProtoBufException.WorkspaceException getWorkspace() {
      return workspace_;
    }
    /**
     * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
     */
    public com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder getWorkspaceOrBuilder() {
      return workspace_;
    }

    private void initFields() {
      message_ = "";
      workspace_ = com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasWorkspace()) {
        if (!getWorkspace().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, workspace_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, workspace_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.ExceptionContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicblox.connect.ProtoBufException.ExceptionContainer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blox.connect.ExceptionContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blox.connect.ExceptionContainer)
        com.logicblox.connect.ProtoBufException.ExceptionContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_ExceptionContainer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_ExceptionContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicblox.connect.ProtoBufException.ExceptionContainer.class, com.logicblox.connect.ProtoBufException.ExceptionContainer.Builder.class);
      }

      // Construct using com.logicblox.connect.ProtoBufException.ExceptionContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWorkspaceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (workspaceBuilder_ == null) {
          workspace_ = com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance();
        } else {
          workspaceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_ExceptionContainer_descriptor;
      }

      public com.logicblox.connect.ProtoBufException.ExceptionContainer getDefaultInstanceForType() {
        return com.logicblox.connect.ProtoBufException.ExceptionContainer.getDefaultInstance();
      }

      public com.logicblox.connect.ProtoBufException.ExceptionContainer build() {
        com.logicblox.connect.ProtoBufException.ExceptionContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicblox.connect.ProtoBufException.ExceptionContainer buildPartial() {
        com.logicblox.connect.ProtoBufException.ExceptionContainer result = new com.logicblox.connect.ProtoBufException.ExceptionContainer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (workspaceBuilder_ == null) {
          result.workspace_ = workspace_;
        } else {
          result.workspace_ = workspaceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicblox.connect.ProtoBufException.ExceptionContainer) {
          return mergeFrom((com.logicblox.connect.ProtoBufException.ExceptionContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicblox.connect.ProtoBufException.ExceptionContainer other) {
        if (other == com.logicblox.connect.ProtoBufException.ExceptionContainer.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasWorkspace()) {
          mergeWorkspace(other.getWorkspace());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (hasWorkspace()) {
          if (!getWorkspace().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicblox.connect.ProtoBufException.ExceptionContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicblox.connect.ProtoBufException.ExceptionContainer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private com.logicblox.connect.ProtoBufException.WorkspaceException workspace_ = com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.logicblox.connect.ProtoBufException.WorkspaceException, com.logicblox.connect.ProtoBufException.WorkspaceException.Builder, com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder> workspaceBuilder_;
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public boolean hasWorkspace() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public com.logicblox.connect.ProtoBufException.WorkspaceException getWorkspace() {
        if (workspaceBuilder_ == null) {
          return workspace_;
        } else {
          return workspaceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public Builder setWorkspace(com.logicblox.connect.ProtoBufException.WorkspaceException value) {
        if (workspaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          workspace_ = value;
          onChanged();
        } else {
          workspaceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public Builder setWorkspace(
          com.logicblox.connect.ProtoBufException.WorkspaceException.Builder builderForValue) {
        if (workspaceBuilder_ == null) {
          workspace_ = builderForValue.build();
          onChanged();
        } else {
          workspaceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public Builder mergeWorkspace(com.logicblox.connect.ProtoBufException.WorkspaceException value) {
        if (workspaceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              workspace_ != com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance()) {
            workspace_ =
              com.logicblox.connect.ProtoBufException.WorkspaceException.newBuilder(workspace_).mergeFrom(value).buildPartial();
          } else {
            workspace_ = value;
          }
          onChanged();
        } else {
          workspaceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public Builder clearWorkspace() {
        if (workspaceBuilder_ == null) {
          workspace_ = com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance();
          onChanged();
        } else {
          workspaceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public com.logicblox.connect.ProtoBufException.WorkspaceException.Builder getWorkspaceBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getWorkspaceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      public com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder getWorkspaceOrBuilder() {
        if (workspaceBuilder_ != null) {
          return workspaceBuilder_.getMessageOrBuilder();
        } else {
          return workspace_;
        }
      }
      /**
       * <code>optional .blox.connect.WorkspaceException workspace = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.logicblox.connect.ProtoBufException.WorkspaceException, com.logicblox.connect.ProtoBufException.WorkspaceException.Builder, com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder> 
          getWorkspaceFieldBuilder() {
        if (workspaceBuilder_ == null) {
          workspaceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.logicblox.connect.ProtoBufException.WorkspaceException, com.logicblox.connect.ProtoBufException.WorkspaceException.Builder, com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder>(
                  getWorkspace(),
                  getParentForChildren(),
                  isClean());
          workspace_ = null;
        }
        return workspaceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:blox.connect.ExceptionContainer)
    }

    static {
      defaultInstance = new ExceptionContainer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:blox.connect.ExceptionContainer)
  }

  public interface WorkspaceExceptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blox.connect.WorkspaceException)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
     */
    com.logicblox.connect.ProtoBufException.WorkspaceException.Code getCode();
  }
  /**
   * Protobuf type {@code blox.connect.WorkspaceException}
   */
  public static final class WorkspaceException extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:blox.connect.WorkspaceException)
      WorkspaceExceptionOrBuilder {
    // Use WorkspaceException.newBuilder() to construct.
    private WorkspaceException(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkspaceException(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkspaceException defaultInstance;
    public static WorkspaceException getDefaultInstance() {
      return defaultInstance;
    }

    public WorkspaceException getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkspaceException(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.logicblox.connect.ProtoBufException.WorkspaceException.Code value = com.logicblox.connect.ProtoBufException.WorkspaceException.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                code_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_WorkspaceException_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_WorkspaceException_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicblox.connect.ProtoBufException.WorkspaceException.class, com.logicblox.connect.ProtoBufException.WorkspaceException.Builder.class);
    }

    public static com.google.protobuf.Parser<WorkspaceException> PARSER =
        new com.google.protobuf.AbstractParser<WorkspaceException>() {
      public WorkspaceException parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkspaceException(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkspaceException> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code blox.connect.WorkspaceException.Code}
     */
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DOES_NOT_EXIST = 1;</code>
       */
      DOES_NOT_EXIST(0, 1),
      /**
       * <code>ALREADY_EXISTS = 2;</code>
       */
      ALREADY_EXISTS(1, 2),
      ;

      /**
       * <code>DOES_NOT_EXIST = 1;</code>
       */
      public static final int DOES_NOT_EXIST_VALUE = 1;
      /**
       * <code>ALREADY_EXISTS = 2;</code>
       */
      public static final int ALREADY_EXISTS_VALUE = 2;


      public final int getNumber() { return value; }

      public static Code valueOf(int value) {
        switch (value) {
          case 1: return DOES_NOT_EXIST;
          case 2: return ALREADY_EXISTS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.logicblox.connect.ProtoBufException.WorkspaceException.getDescriptor().getEnumTypes().get(0);
      }

      private static final Code[] VALUES = values();

      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:blox.connect.WorkspaceException.Code)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private com.logicblox.connect.ProtoBufException.WorkspaceException.Code code_;
    /**
     * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
     */
    public com.logicblox.connect.ProtoBufException.WorkspaceException.Code getCode() {
      return code_;
    }

    private void initFields() {
      name_ = "";
      code_ = com.logicblox.connect.ProtoBufException.WorkspaceException.Code.DOES_NOT_EXIST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, code_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicblox.connect.ProtoBufException.WorkspaceException parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicblox.connect.ProtoBufException.WorkspaceException prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blox.connect.WorkspaceException}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blox.connect.WorkspaceException)
        com.logicblox.connect.ProtoBufException.WorkspaceExceptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_WorkspaceException_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_WorkspaceException_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicblox.connect.ProtoBufException.WorkspaceException.class, com.logicblox.connect.ProtoBufException.WorkspaceException.Builder.class);
      }

      // Construct using com.logicblox.connect.ProtoBufException.WorkspaceException.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.logicblox.connect.ProtoBufException.WorkspaceException.Code.DOES_NOT_EXIST;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicblox.connect.ProtoBufException.internal_static_blox_connect_WorkspaceException_descriptor;
      }

      public com.logicblox.connect.ProtoBufException.WorkspaceException getDefaultInstanceForType() {
        return com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance();
      }

      public com.logicblox.connect.ProtoBufException.WorkspaceException build() {
        com.logicblox.connect.ProtoBufException.WorkspaceException result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicblox.connect.ProtoBufException.WorkspaceException buildPartial() {
        com.logicblox.connect.ProtoBufException.WorkspaceException result = new com.logicblox.connect.ProtoBufException.WorkspaceException(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicblox.connect.ProtoBufException.WorkspaceException) {
          return mergeFrom((com.logicblox.connect.ProtoBufException.WorkspaceException)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicblox.connect.ProtoBufException.WorkspaceException other) {
        if (other == com.logicblox.connect.ProtoBufException.WorkspaceException.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicblox.connect.ProtoBufException.WorkspaceException parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicblox.connect.ProtoBufException.WorkspaceException) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private com.logicblox.connect.ProtoBufException.WorkspaceException.Code code_ = com.logicblox.connect.ProtoBufException.WorkspaceException.Code.DOES_NOT_EXIST;
      /**
       * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
       */
      public com.logicblox.connect.ProtoBufException.WorkspaceException.Code getCode() {
        return code_;
      }
      /**
       * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
       */
      public Builder setCode(com.logicblox.connect.ProtoBufException.WorkspaceException.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .blox.connect.WorkspaceException.Code code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = com.logicblox.connect.ProtoBufException.WorkspaceException.Code.DOES_NOT_EXIST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:blox.connect.WorkspaceException)
    }

    static {
      defaultInstance = new WorkspaceException(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:blox.connect.WorkspaceException)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blox_connect_ExceptionContainer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_blox_connect_ExceptionContainer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blox_connect_WorkspaceException_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_blox_connect_WorkspaceException_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034blox/connect/Exception.proto\022\014blox.con" +
      "nect\"Z\n\022ExceptionContainer\022\017\n\007message\030\001 " +
      "\002(\t\0223\n\tworkspace\030\002 \001(\0132 .blox.connect.Wo" +
      "rkspaceException\"\207\001\n\022WorkspaceException\022" +
      "\014\n\004name\030\001 \002(\t\0223\n\004code\030\002 \002(\0162%.blox.conne" +
      "ct.WorkspaceException.Code\".\n\004Code\022\022\n\016DO" +
      "ES_NOT_EXIST\020\001\022\022\n\016ALREADY_EXISTS\020\002B,\n\025co" +
      "m.logicblox.connectB\021ProtoBufExceptionH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_blox_connect_ExceptionContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blox_connect_ExceptionContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_blox_connect_ExceptionContainer_descriptor,
        new java.lang.String[] { "Message", "Workspace", });
    internal_static_blox_connect_WorkspaceException_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_blox_connect_WorkspaceException_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_blox_connect_WorkspaceException_descriptor,
        new java.lang.String[] { "Name", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
